### ISSUE TITLE
Transfer der Anpassungen von Blog auf Pinnwand

### ISSUE THREAD

**Issue by loechel** [loechel/lmu.contenttypes.pinnwand#1]
Generische Elemente bitte in lmu.policy.base auslagern.

Screenskribbles für pinnwand_entryview und frontpage_view können wir nachliefern wenn notwendig.

**Comment by reinhardt** [comment]
Habe drei Pull-Requests in den drei beteiligten Paketen angelegt:

https://github.com/loechel/lmu.policy.base/pull/14
https://github.com/loechel/lmu.contenttypes.blog/pull/31
https://github.com/loechel/lmu.contenttypes.pinnwand/pull/2

Das in der Policy sollte zuerst gemerged werden, bzw. idealerweise alle zusammen.

**Comment by loechel** [comment]
merged und alle views upgedated
