### ISSUE TITLE
DefaultFactorys für Pinnwand Entry 

### ISSUE THREAD

**Issue by loechel** [loechel/lmu.contenttypes.pinnwand#3]
Beim Live System greifen im moment die Default factories nicht, bitte prüfen

Schema bitte ändern / form anpassen,
dass: 
IPublication.expires required ist, ebenso pinnwand_entry_type

expires, bitte mit datum heute + 14 Tage 24:00 Uhr vorbelegen. 

ggf. validator für expires, soll nicht größer als 6 Monate in Zukunft sein.

**Comment by reinhardt** [comment]
"expires" ist jetzt ein Feld im Pinnwand-Schema, das Feld aus dem IPublication-Behavior wird ausgeblendet. Weiß nicht, ob das die eleganteste Lösung ist, scheint aber gut zu funktionieren und ist flexibel. Einen Validator hinzu zu fügen war so auch relativ einfach. Ist alles in master.

**Comment by loechel** [comment]
greift dann auch die Plone logik das er einen Beitrag nicht mehr anzeigt, wenn das expires abläuft?

**Comment by reinhardt** [comment]
Wo wird die denn benutzt? In den Listings?
Ich denke, wenn es auf dem Schema des Content-Types ein Feld gibt, dann bekommt das Vorrang vor etwaigen Behaviors. Aber guter Punkt, müsste ich nochmal nach schauen. Ich kann mich auch dunkel an eine Diskussion auf der Mailing-Liste über das Thema erinnern.
